### ISSUE TITLE
Updating speed not working

### ISSUE THREAD

**Issue by edwardhadders** [CoMPaTech/esphome_c1101#13]
When i change the speed with the original remote this change will not been seen by esphome, i dont know if this is by design or there something going wrong.

**Comment by CoMPaTech** [comment]
Top of mind quick answer, they obviously need to 'hear' each other (so if you bring the c1101 closer to the remote) and you explicitly need that additional wire from the diagram (and the board supporting it)

**Comment by edwardhadders** [comment]
Thank you for your quick reaction, i have the remote next to the receiver that should not be the problem.
I connected all the wires like the manual said. i only did not connect the GDO0 is this the problem?

**Comment by CoMPaTech** [comment]
(not trying to be deflective, just tired after a long day) - could you sift through #8 I think it still has some blurry images of my contraption - I just confirmed I still see the 'change of speed' when pressing a wall button but I never got 'which remote' to work. If memory serves correctly (otherwise I'll have a look for you tomorrow) the GD0 is not connected on my side as well and the other GD is connected as that would be the one receiving data on

**Comment by edwardhadders** [comment]
Hallo Tom ik zie dat je ook uit nederland komt dus dit gaat wat makkelijker, ik gebruik een nodemcu v3 en zag dat in de esphome configuratie stond d1 mini dit heb ik aangepast en nu krijg ik deze fout bij het installeren.
kan het hierdoor fout gaan?

Compiling .pioenvs/esp-eh-02/lib67b/ESP8266WiFi/ESP8266WiFiMulti.cpp.o
In file included from src/main.cpp:72:
src/fancontrol.h: In member function 'virtual void FanRecv::setup()':
src/fancontrol.h:41:15: error: 'D1' was not declared in this scope; did you mean 'y1'?
   41 |       pinMode(D1, INPUT);
      |               ^~
      |               y1

**Comment by CoMPaTech** [comment]
Dat is wazig, een NodeMCU3 heeft toch ook een 'label' D1 op de print staan? (De oudere in elk geval wel)

**Comment by edwardhadders** [comment]
Ja klopt op nodemcu v3 zit gewoon d1 tot d8 poort

**Comment by CoMPaTech** [comment]
Bijzonder, nog niet eerder tegengekomen, maar ik 'expose' 'm ook niet zoals je bijvoorbeeld vanuit https://forum.dangerousthings.com/t/access-control-with-esphome-home-assistant-and-node-red/13907/15 ziet met die Wiegand component. Maar je zou idd D0 t/m D8 moeten hebben wat ik op ESPhome zelf lees; heb je in de configuratie als board type `nodemcuv2` geprobeerd? (Ondanks dat je een v3) hebt? De melding lijkt te impliceren dat hij een board-type gebruikt waarbij de pinnen niet zijn voorgesteld.

**Comment by edwardhadders** [comment]
sorry voor de late reactie, maar met de aanpassing naar nodemcuv2 lijkt het te werken ik krijg nu keurig de status door.
bedankt voor je hulp.

**Comment by CoMPaTech** [comment]
Super, goed om
Te horen
