### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by countjuh** [CoMPaTech/esphome_c1101#9]
Good morning. Good to read you rewrote the itho fancontrol. i was trying to find a solution and here it is.
only thin, i get a compiling error.

''
Compiling /data/fancontrol/.pioenvs/fancontrol/libd10/esphome_itho/CC1101.cpp.o
In file included from /data/fancontrol/.piolibdeps/fancontrol/esphome_itho/CC1101.cpp:5:
/data/fancontrol/.piolibdeps/fancontrol/esphome_itho/CC1101.h:10:10: fatal error: SPI.h: No such file or directory

*************************************************************
* Looking for SPI.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:SPI.h"
* Web  > https://registry.platformio.org/search?q=header:SPI.h
*
*************************************************************

   10 | #include <SPI.h>
      |          ^~~~~~~
compilation terminated.
*** [/data/fancontrol/.pioenvs/fancontrol/libd10/esphome_itho/CC1101.cpp.o] Error 1
========================= [FAILED] Took 325.43 seconds =========================
''

**Comment by CoMPaTech** [comment]
Are you sure you have `SPI` in the `libraries` section of your yaml? It should automatically pick up from it? See https://github.com/esphome/issues/issues/2911 for a likewise troubleshoot if that helps

```
  libraries: 
    - https://github.com/CoMPaTech/esphome_itho.git
    - Ticker
    - SPI
```

**Comment by countjuh** [comment]
It think it is correct:

''
esphome:
  name: fancontrol
  platform: ESP8266
  board: d1_mini_pro
  includes: 
    - ITHO/fancontrol.h
  
  libraries: 
    - https://github.com/CoMPaTech/esphome_itho.git
    - Ticker
    - SPI

wifi:
  ssid: "*****" 
  password: "******"

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: 'jqSTIbQoK2rkoydI4mHbejLoYCChZGxpabv80sFeyeE='

ota:
  password: 'fan'

**Comment by countjuh** [comment]
putting -SPI on top library it works! thanks!

**Comment by CoMPaTech** [comment]
I'll update accordingly, thanks for testing it out!

**Comment by countjuh** [comment]
Nice. one last question. It works. the remote control uses automatic function which i always activate. fanspeed now react on the internal humidity sensor. In de programming i dont see this command to the itho. Is it something for the future? for the rest, thanks again, working good :)

**Comment by CoMPaTech** [comment]
I don't have the fancier unit so not sure how the ones with humidity function. I'd have to look up how it works
